# Site settings
title: Wilko Graf von Hardenberg
email: wilko.hardenberg@gmail.com
description: Modern historian, unexpected geek, wannabe naturalist, sauntering explorer, and more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wilkohardenberg.net" # the base hostname & protocol for your site
twitter_username: wilkohardenberg
github_username: wilkohardenberg

# Build settings
markdown: kramdown

collections:
  journal:
    output: true
    permalink: /journal/:path/
